import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const translations = {
  es: {
    // Header
    "nav.home": "Inicio",
    "nav.about": "Nosotros",
    "nav.services": "Sectores",
    "nav.fleet": "Flota",
    "nav.testimonials": "Testimonios",
    "nav.contact": "Contacto",
    "header.cta": "Cotiza Ahora",

    // Hero
    "hero.title": "Baños Portátiles y Trailers de Lujo en California",
    "hero.subtitle": "Limpieza, Puntualidad y Confianza.",
    "hero.description": "Más de 10 años ofreciendo soluciones confiables para bodas, eventos, construcciones y producciones.",
    "hero.cta": "Cotiza Ahora",
    "hero.call": "Llámanos",

    // About
    "about.eyebrow": "/Sobre nosotros",
    "about.title": "Sobre KENO Portable",
    "about.heading": "Más de 20 años de experiencia, dedicación y valores familiares",
    "about.subtitle": "Una historia de esfuerzo, familia y dedicación",
    "about.paragraph1": "Durante más de veinte años, Jorge vivió una rutina marcada por largas jornadas laborales y días que comenzaban temprano y terminaban tarde. Ese tiempo lo formó como padre, esposo, hombre de familia y trabajador íntegro, acumulando una profunda experiencia en su industria.",
    "about.paragraph2": "Con esa trayectoria, tomó una decisión valiente: crear su propia compañía en la tierra de las oportunidades. El camino no fue fácil, pero siempre contó con el respaldo de su familia. Su hija Myriam fue un apoyo fundamental en el área administrativa, aportando ideas, incluido el nombre de la empresa y asistencia con el idioma. Santa, su esposa y socia, fue el sostén emocional que lo impulsó a seguir adelante.",
    "about.paragraph3": "Para consolidar el proyecto, Jorge encontró el aliado ideal en su hermano Raúl, con cinco años de experiencia y el apoyo de sus propios hijos como parte del equipo. Así, Jorge, Santa y Raúl unieron experiencia, confianza y valores familiares para fundar Keno Portable Services, una empresa comprometida con brindar soluciones esenciales a sus clientes, siempre con calidad y dedicación.",
    "about.readMore": "Leer historia completa ↓",
    "about.readLess": "Leer menos ↑",
    "about.cta": "Trabaja con Nosotros",
    "about.pillCta": "Contáctanos",
    "about.imageAlt": "Equipo familiar de KENO Portable Services",

    // Services / Sectores
    "services.title": "Sectores que Atendemos",
    "services.subtitle": "Soluciones profesionales adaptadas a cada necesidad.",
    "services.events.title": "Eventos & Bodas",
    "services.events.description": "Trailers de lujo y baños elegantes que complementan perfectamente tu evento especial.",
    "services.events.feature1": "Trailers VIP",
    "services.events.feature2": "Diseño elegante",
    "services.events.feature3": "Servicio premium",
    "services.construction.title": "Construcción & Industrial",
    "services.construction.description": "Renta mensual con servicio de mantenimiento regular para tus proyectos de construcción.",
    "services.construction.feature1": "Contratos mensuales",
    "services.construction.feature2": "Mantenimiento incluido",
    "services.construction.feature3": "Unidades resistentes",
    "services.production.title": "Producciones & Filmaciones",
    "services.production.description": "Logística profesional y discreta para sets de filmación y producciones.",
    "services.production.feature1": "Configuración flexible",
    "services.production.feature2": "Servicio silencioso",
    "services.production.feature3": "Entregas coordinadas",
    "services.emergency.title": "Emergencias & Largo Plazo",
    "services.emergency.description": "Respuesta rápida y confiable para situaciones de emergencia o necesidades extendidas.",
    "services.emergency.feature1": "Disponibilidad 24/7",
    "services.emergency.feature2": "Respuesta inmediata",
    "services.emergency.feature3": "Contratos flexibles",
    "services.cardCta": "Cotizar para este sector →",
    "services.cta": "Solicitar Información",

    // Fleet
    "fleet.eyebrow": "• FLOTA MODERNA",
    "fleet.title": "Equipamiento de primer nivel para cada exigencia",
    "fleet.subtitle": "Unidades impecables, higienizadas y listas para operar con los más altos estándares de confort y sanidad en toda California.",
    "fleet.quoteBtn": "Cotizar este modelo →",

    "fleet.tab.luxury": "Trailer de Lujo",
    "fleet.luxury.title": "Trailer de Lujo",
    "fleet.luxury.badge": "VIP Luxury",
    "fleet.luxury.description": "Experiencia premium con acabados modernos, aire acondicionado y diseño elegante.",
    "fleet.luxury.bullet1": "Aire acondicionado",
    "fleet.luxury.bullet2": "Acabados premium",
    "fleet.luxury.bullet3": "Iluminación LED",

    "fleet.tab.standard": "Baño Estándar",
    "fleet.standard.title": "Baño Estándar",
    "fleet.standard.badge": "Standard",
    "fleet.standard.description": "Unidades básicas de alta calidad, perfectas para construcción y eventos al aire libre.",
    "fleet.standard.bullet1": "Limpieza garantizada",
    "fleet.standard.bullet2": "Resistente y duradero",
    "fleet.standard.bullet3": "Ventilación adecuada",

    "fleet.tab.ada": "Baño ADA Accesible",
    "fleet.ada.title": "Baño ADA Accesible",
    "fleet.ada.badge": "ADA Compliance",
    "fleet.ada.description": "Cumplimiento completo con regulaciones ADA, espacioso y con rampa de acceso.",
    "fleet.ada.bullet1": "Rampa de acceso",
    "fleet.ada.bullet2": "Espacio amplio",
    "fleet.ada.bullet3": "Barras de apoyo",

    "fleet.tab.handwash": "Estación de Lavado",
    "fleet.handwash.title": "Estación de Lavado",
    "fleet.handwash.badge": "Hygiene+",
    "fleet.handwash.description": "Estaciones dobles de lavado de manos para mantener la higiene en todo momento.",
    "fleet.handwash.bullet1": "Doble lavabo",
    "fleet.handwash.bullet2": "Dispensador de jabón",
    "fleet.handwash.bullet3": "Toallas de papel",

    // Why Choose Us
    "why.eyebrow": "• POR QUÉ ELEGIRNOS",
    "why.title": "Por Qué Elegir Keno",
    "why.subtitle": "Compromiso, puntualidad y servicio excepcional para cada evento u obra en California.",
    "why.experience.title": "10+ Años de Experiencia",
    "why.experience.description": "Líderes en California con más de una década de servicio profesional.",
    "why.fleet.title": "Flota Moderna",
    "why.fleet.description": "Unidades estándar, deluxe, ADA y trailers VIP impecables.",
    "why.delivery.title": "Entregas Rápidas",
    "why.delivery.description": "Logística y mantenimiento puntual cuando lo necesitas.",
    "why.support.title": "Atención 24/7",
    "why.support.description": "Soporte y respuesta inmediata en todo momento.",
    "why.imageBadge": "Servicio Certificado en California",

    // Testimonials
    "testimonials.title": "Lo Que Dicen Nuestros Clientes",
    "testimonials.subtitle": "Nuestros clientes confían en nosotros por nuestra puntualidad, limpieza y compromiso.",

    // Contact
    "contact.tag": "• CONTACTO",
    "contact.heading": "Solicita tu servicio",
    "contact.headingHighlight": "hoy mismo.",
    "contact.description": "Estamos listos para ayudarte con tu evento, obra o proyecto especial. Completa el formulario y nos comunicaremos contigo lo antes posible.",
    "contact.title": "Solicita Tu Cotización",
    "contact.subtitle": "Estamos listos para ayudarte. Contáctanos hoy mismo.",
    "contact.location": "Ubicación",
    "contact.location.value": "California, USA",
    "contact.location.subvalue": "Servicio en todo el estado",
    "contact.phone": "Teléfono",
    "contact.phone.value": "(858) 328-9815",
    "contact.email": "Email",
    "contact.email.value": "customer@kenoportableservices.us",
    "contact.hours": "Horario",
    "contact.hours.value": "Lunes - Domingo",
    "contact.hours.subvalue": "Disponible 24/7",
    "contact.form.name": "Nombre Completo",
    "contact.form.namePlaceholder": "Tu nombre",
    "contact.form.phone": "Teléfono",
    "contact.form.phonePlaceholder": "(555) 000-0000",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "tu@email.com",
    "contact.form.sectorLabel": "Sector o Proyecto",
    "contact.form.sectorPlaceholder": "Selecciona un sector...",
    "contact.form.sectorEvents": "Eventos & Bodas",
    "contact.form.sectorConstruction": "Construcción & Obra",
    "contact.form.sectorProduction": "Producciones & Filmaciones",
    "contact.form.sectorEmergency": "Emergencias & Largo Plazo",
    "contact.form.sectorOther": "Otro",
    "contact.form.unitLabel": "Unidad de Interés",
    "contact.form.unitPlaceholder": "Cualquier unidad / Asesoría",
    "contact.form.unitAny": "Cualquier unidad / Asesoría",
    "contact.form.unitVip": "Trailer Ejecutivo VIP",
    "contact.form.unitStandard": "Baño Estándar",
    "contact.form.unitAda": "Baño ADA Accesible",
    "contact.form.unitHandwash": "Estación Doble de Lavado",
    "contact.form.unitCombo": "Paquete Combinado (Múltiples)",
    "contact.form.eventType": "Sector o Proyecto",
    "contact.form.eventTypePlaceholder": "Selecciona una opción...",
    "contact.form.eventDate": "Fecha Estimada",
    "contact.form.guests": "Personas / Capacidad aprox.",
    "contact.form.guestsPlaceholder": "Ej. 50 - 150",
    "contact.form.message": "Mensaje Adicional",
    "contact.form.messagePlaceholder": "Cuéntanos más sobre tu proyecto o necesidades específicas...",
    "contact.form.submit": "Enviar Solicitud",
    "contact.form.events": "Eventos & Bodas",
    "contact.form.construction": "Construcción & Obra",
    "contact.form.production": "Producciones & Filmaciones",
    "contact.form.emergency": "Emergencias / Largo Plazo",
    "contact.form.trailer": "Trailer VIP de Lujo",
    "contact.form.standard": "Baño Estándar",
    "contact.form.ada": "Baño ADA Accesible",
    "contact.form.handwash": "Estación de Lavado",
    "contact.form.wedding": "Eventos & Bodas",
    "contact.form.corporate": "Evento Corporativo",
    "contact.form.other": "Otro",
    "contact.form.success": "¡Mensaje enviado!",
    "contact.form.successMessage": "Nos pondremos en contacto contigo pronto.",
    "contact.form.error": "Error en el formulario",
    "contact.form.errorMessage": "Por favor revisa los campos e intenta nuevamente.",

    // Footer
    "footer.description": "Más de 10 años ofreciendo soluciones sanitarias profesionales en California.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.services": "Servicios",
    "footer.contact": "Contacto",
    "footer.eventsWeddings": "Eventos & Bodas",
    "footer.construction": "Construcción",
    "footer.productions": "Producciones",
    "footer.emergencies": "Emergencias",
    "footer.longTerm": "Largo Plazo",
    "footer.rights": "Todos los derechos reservados.",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
  },
  en: {
    // Header
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Industries",
    "nav.fleet": "Fleet",
    "nav.testimonials": "Testimonials",
    "nav.contact": "Contact",
    "header.cta": "Get a Quote",

    // Hero
    "hero.title": "Portable Restrooms & Luxury Trailers in California",
    "hero.subtitle": "Cleanliness, Punctuality and Trust.",
    "hero.description": "Over 10 years providing reliable solutions for weddings, events, construction sites and productions.",
    "hero.cta": "Get a Quote",
    "hero.call": "Call Us",

    // About
    "about.eyebrow": "/About us",
    "about.title": "About KENO Portable",
    "about.heading": "Over 20 years of experience, dedication and family values",
    "about.subtitle": "A story of hard work, family and dedication",
    "about.paragraph1": "For more than twenty years, Jorge lived a routine marked by long work days that started early and ended late. That time shaped him as a father, husband, family man and honest worker, accumulating deep experience in his industry.",
    "about.paragraph2": "With that background, he made a brave decision: to create his own company in the land of opportunities. The path wasn't easy, but he always had his family's support. His daughter Myriam was fundamental in the administrative area, contributing ideas, including the company name and language assistance. Santa, his wife and partner, was the emotional support that pushed him forward.",
    "about.paragraph3": "To consolidate the project, Jorge found the ideal ally in his brother Raúl, with five years of experience and the support of his own children as part of the team. Thus, Jorge, Santa and Raúl united experience, trust and family values to found Keno Portable Services, a company committed to providing essential solutions to its customers, always with quality and dedication.",
    "about.readMore": "Read full story ↓",
    "about.readLess": "Read less ↑",
    "about.cta": "Work With Us",
    "about.pillCta": "Contact Us",
    "about.imageAlt": "KENO Portable Services family team",

    // Services / Industries
    "services.title": "Industries We Serve",
    "services.subtitle": "Professional solutions tailored to every need.",
    "services.events.title": "Events & Weddings",
    "services.events.description": "Luxury trailers and elegant restrooms that perfectly complement your special event.",
    "services.events.feature1": "VIP Trailers",
    "services.events.feature2": "Elegant design",
    "services.events.feature3": "Premium service",
    "services.construction.title": "Construction & Industrial",
    "services.construction.description": "Monthly rental with regular maintenance service for your construction projects.",
    "services.construction.feature1": "Monthly contracts",
    "services.construction.feature2": "Maintenance included",
    "services.construction.feature3": "Durable units",
    "services.production.title": "Productions & Filming",
    "services.production.description": "Professional and discreet logistics for film sets and productions.",
    "services.production.feature1": "Flexible setup",
    "services.production.feature2": "Quiet service",
    "services.production.feature3": "Coordinated deliveries",
    "services.emergency.title": "Emergencies & Long Term",
    "services.emergency.description": "Fast and reliable response for emergency situations or extended needs.",
    "services.emergency.feature1": "24/7 availability",
    "services.emergency.feature2": "Immediate response",
    "services.emergency.feature3": "Flexible contracts",
    "services.cardCta": "Get quote for this sector →",
    "services.cta": "Request Information",

    // Fleet
    "fleet.eyebrow": "• MODERN FLEET",
    "fleet.title": "Top-tier equipment for every demand",
    "fleet.subtitle": "Impeccable, sanitized units ready to deploy with the highest standards of comfort and sanitation across California.",
    "fleet.quoteBtn": "Get quote for this model →",

    "fleet.tab.luxury": "Luxury Trailer",
    "fleet.luxury.title": "Luxury Trailer",
    "fleet.luxury.badge": "VIP Luxury",
    "fleet.luxury.description": "Premium experience with modern finishes, air conditioning and elegant design.",
    "fleet.luxury.bullet1": "Air conditioning",
    "fleet.luxury.bullet2": "Premium finishes",
    "fleet.luxury.bullet3": "LED lighting",

    "fleet.tab.standard": "Standard Restroom",
    "fleet.standard.title": "Standard Restroom",
    "fleet.standard.badge": "Standard",
    "fleet.standard.description": "High-quality basic units, perfect for construction and outdoor events.",
    "fleet.standard.bullet1": "Guaranteed cleanliness",
    "fleet.standard.bullet2": "Sturdy and durable",
    "fleet.standard.bullet3": "Proper ventilation",

    "fleet.tab.ada": "ADA Accessible Restroom",
    "fleet.ada.title": "ADA Accessible Restroom",
    "fleet.ada.badge": "ADA Compliance",
    "fleet.ada.description": "Full compliance with ADA regulations, spacious with access ramp.",
    "fleet.ada.bullet1": "Access ramp",
    "fleet.ada.bullet2": "Ample space",
    "fleet.ada.bullet3": "Support bars",

    "fleet.tab.handwash": "Handwash Station",
    "fleet.handwash.title": "Handwash Station",
    "fleet.handwash.badge": "Hygiene+",
    "fleet.handwash.description": "Dual handwash stations to maintain hygiene at all times.",
    "fleet.handwash.bullet1": "Double sink",
    "fleet.handwash.bullet2": "Soap dispenser",
    "fleet.handwash.bullet3": "Paper towels",

    // Why Choose Us
    "why.eyebrow": "• WHY CHOOSE US",
    "why.title": "Why Choose Keno",
    "why.subtitle": "Commitment, punctuality, and exceptional service for every event and project in California.",
    "why.experience.title": "10+ Years of Experience",
    "why.experience.description": "Leaders in California with over a decade of professional service.",
    "why.fleet.title": "Modern Fleet",
    "why.fleet.description": "Standard, deluxe, ADA, and VIP trailers in immaculate condition.",
    "why.delivery.title": "Fast Deliveries",
    "why.delivery.description": "Punctual logistics and maintenance right when you need it.",
    "why.support.title": "24/7 Support",
    "why.support.description": "Immediate support and assistance around the clock.",
    "why.imageBadge": "Certified California Service",

    // Testimonials
    "testimonials.title": "What Our Clients Say",
    "testimonials.subtitle": "Our clients trust us for our punctuality, cleanliness and commitment.",

    // Contact
    "contact.tag": "• CONTACT",
    "contact.heading": "Request your service",
    "contact.headingHighlight": "today.",
    "contact.description": "We're ready to help with your event, construction site or special project. Fill out the form and we'll get back to you as soon as possible.",
    "contact.title": "Request Your Quote",
    "contact.subtitle": "We're ready to help you. Contact us today.",
    "contact.location": "Location",
    "contact.location.value": "California, USA",
    "contact.location.subvalue": "Statewide service",
    "contact.phone": "Phone",
    "contact.phone.value": "(858) 328-9815",
    "contact.email": "Email",
    "contact.email.value": "customer@kenoportableservices.us",
    "contact.hours": "Hours",
    "contact.hours.value": "Monday - Sunday",
    "contact.hours.subvalue": "Available 24/7",
    "contact.form.name": "Full Name",
    "contact.form.namePlaceholder": "Your name",
    "contact.form.phone": "Phone",
    "contact.form.phonePlaceholder": "(555) 000-0000",
    "contact.form.email": "Email",
    "contact.form.emailPlaceholder": "your@email.com",
    "contact.form.sectorLabel": "Sector or Project",
    "contact.form.sectorPlaceholder": "Select a sector...",
    "contact.form.sectorEvents": "Events & Weddings",
    "contact.form.sectorConstruction": "Construction & Job Sites",
    "contact.form.sectorProduction": "Productions & Filming",
    "contact.form.sectorEmergency": "Emergencies & Long Term",
    "contact.form.sectorOther": "Other",
    "contact.form.unitLabel": "Unit of Interest",
    "contact.form.unitPlaceholder": "Any unit / Consultation",
    "contact.form.unitAny": "Any unit / Consultation",
    "contact.form.unitVip": "VIP Executive Trailer",
    "contact.form.unitStandard": "Standard Restroom",
    "contact.form.unitAda": "ADA Accessible Restroom",
    "contact.form.unitHandwash": "Double Handwash Station",
    "contact.form.unitCombo": "Combined Package (Multiple)",
    "contact.form.eventType": "Sector or Project",
    "contact.form.eventTypePlaceholder": "Select an option...",
    "contact.form.eventDate": "Estimated Date",
    "contact.form.guests": "People / Approx. Capacity",
    "contact.form.guestsPlaceholder": "Ex. 50 - 150",
    "contact.form.message": "Additional Message",
    "contact.form.messagePlaceholder": "Tell us more about your project or specific needs...",
    "contact.form.submit": "Send Request",
    "contact.form.events": "Events & Weddings",
    "contact.form.construction": "Construction & Job Sites",
    "contact.form.production": "Productions & Filming",
    "contact.form.emergency": "Emergencies / Long Term",
    "contact.form.trailer": "VIP Luxury Trailer",
    "contact.form.standard": "Standard Restroom",
    "contact.form.ada": "ADA Accessible Restroom",
    "contact.form.handwash": "Handwash Station",
    "contact.form.wedding": "Events & Weddings",
    "contact.form.corporate": "Corporate Event",
    "contact.form.other": "Other",
    "contact.form.success": "Message sent!",
    "contact.form.successMessage": "We'll get in touch with you soon.",
    "contact.form.error": "Form error",
    "contact.form.errorMessage": "Please verify your fields and try again.",

    // Footer
    "footer.description": "Over 10 years providing professional sanitary solutions in California.",
    "footer.quickLinks": "Quick Links",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.eventsWeddings": "Events & Weddings",
    "footer.construction": "Construction",
    "footer.productions": "Productions",
    "footer.emergencies": "Emergencies",
    "footer.longTerm": "Long Term",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("es");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations["es"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
